import {Component,inject,signal} from '@angular/core';
import {DecimalPipe} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {Router,RouterLink} from '@angular/router';
import {firstValueFrom} from 'rxjs';
import {ApiClient,errorMessage} from '../../core/api';
import {AuthService} from '../../core/auth';
import {Icon} from '../../shared/icon';
import {AlertFocus} from '../../shared/alert-focus';
type Row=Record<string,any>;
@Component({selector:'mapan-new-analysis',imports:[FormsModule,RouterLink,Icon,DecimalPipe,AlertFocus],template:`
<header class="page-heading"><div><span class="eyebrow">NUEVO ANÁLISIS / PASO 1 DE 5</span><h1>Empecemos por el cliente</h1><p>Selecciona a quién vas a analizar y define la operación de crédito.</p></div><a class="text-action" routerLink="/solicitudes">Ver solicitudes</a></header>
@if(error()){<p class="error" role="alert" mapanAlertFocus>{{error()}}</p>}@if(loading()){<p role="status" class="loading-block">Preparando productos y sucursales…</p>}
<div class="result-grid"><section class="panel"><div class="section-title"><span class="icon-tile"><m-icon name="clients"/></span><h2>Cliente</h2></div>
@if(selected();as c){<div class="selected-customer"><span class="avatar">{{name(c).slice(0,1)}}</span><div><h3>{{name(c)}}</h3><p>{{c['numeroIdentificacion']}}</p></div><button class="ghost compact" (click)="selected.set(null)">Cambiar</button></div>}
@else{<label for="customer-search">Identificación o nombre</label><div class="toolbar"><input id="customer-search" [(ngModel)]="search" (keyup.enter)="find()" placeholder="Escribe para buscar un cliente"><button class="secondary" [disabled]="busy()||!search.trim()" (click)="find()"><m-icon name="search"/>Buscar</button></div>@for(c of clients();track c['clienteId']){<button class="select-row" (click)="selected.set(c);creating.set(false)"><span><strong>{{name(c)}}</strong><small>{{c['numeroIdentificacion']}}</small></span><m-icon name="plus"/></button>}@if(searched()&&!clients().length){<p>No encontramos un cliente con esos datos.</p>}@if(auth.can('Clientes:Create')){<button class="text-action ghost" (click)="creating.set(!creating())"><m-icon name="plus"/>Registrar un cliente nuevo</button>}}
@if(creating()&&!selected()){<form class="editor-surface" (ngSubmit)="createClient()" #cf="ngForm"><label>Tipo de persona<select name="person" [(ngModel)]="client['tipoPersona']"><option>NATURAL</option><option>JURIDICA</option></select></label><div class="grid-form"><label>Tipo de identificación<input name="type" [(ngModel)]="client['tipoIdentificacion']" required maxlength="20" placeholder="Ej. CÉDULA / RUC"></label><label>Identificación<input name="number" [(ngModel)]="client['numeroIdentificacion']" required maxlength="30"></label>@if(client['tipoPersona']==='NATURAL'){<label>Nombres<input name="names" [(ngModel)]="client['nombres']" required maxlength="150"></label><label>Apellidos<input name="surnames" [(ngModel)]="client['apellidos']" required maxlength="150"></label>}@else{<label>Razón social<input name="legal" [(ngModel)]="client['razonSocial']" required maxlength="200"></label>}</div><button [disabled]="busy()||cf.invalid">Guardar y seleccionar cliente</button></form>}
<div class="inline-note"><m-icon name="shield"/>El expediente y su información pertenecen únicamente a la empresa activa.</div></section>
<section class="panel"><div class="section-title"><span class="icon-tile"><m-icon name="loan"/></span><h2>Operación de crédito</h2></div><form (ngSubmit)="save()" #form="ngForm"><label>Producto<select name="product" [(ngModel)]="request['productoCreditoId']" required (ngModelChange)="simulate()"><option value="">Selecciona un producto</option>@for(p of products();track p['productoCreditoId']){<option [value]="p['productoCreditoId']">{{p['nombre']}}@if(p['tasaInteresAnualPct']){ · {{p['tasaInteresAnualPct']|number:'1.0-2'}}% anual}</option>}</select></label><div class="grid-form"><label>Monto solicitado<input name="amount" type="number" min="0.01" step="0.01" [(ngModel)]="request['montoSolicitado']" required placeholder="0.00" (ngModelChange)="simulate()"></label><label>Plazo en meses<input name="term" type="number" min="1" step="1" [(ngModel)]="request['plazoSolicitadoMeses']" required placeholder="12" (ngModelChange)="simulate()"></label><label>Sucursal<select name="branch" [(ngModel)]="request['sucursalId']" required><option value="">Seleccionar sucursal</option>@for(b of branches();track b['sucursalId']){<option [value]="b['sucursalId']">{{b['nombre']}}</option>}</select></label></div>
@if(simulando()){<p role="status" class="loading-block">Calculando cuota con la tasa del producto…</p>}
@else if(simulacionError()){<p class="error" role="alert" mapanAlertFocus>{{simulacionError()}}</p>}
@else if(simulacion();as s){<div class="calculo-preview"><div><span>Capital mensual</span><strong>{{s['capitalMensual']|number:'1.2-2'}}</strong></div><div><span>Interés mensual</span><strong>{{s['interesMensual']|number:'1.2-2'}}</strong></div><div><span>Cuota estimada</span><strong>{{s['cuotaEstimada']|number:'1.2-2'}}</strong></div><div><span>Interés total</span><strong>{{s['interesTotal']|number:'1.2-2'}}</strong></div><div><span>Total a pagar</span><strong>{{s['totalAPagar']|number:'1.2-2'}}</strong></div></div>}
<label>Destino del crédito<textarea name="purpose" [(ngModel)]="request['destinoCredito']" maxlength="500" rows="3" placeholder="¿Para qué utilizará el crédito?"></textarea></label><details><summary>Referencia de la solicitud</summary><label>Número de solicitud<input name="reference" [(ngModel)]="request['numeroSolicitud']" required maxlength="50"></label></details><p class="hint">La cuota se calcula con la tasa vigente del producto; este cálculo es solo una vista previa — el backend recalcula y guarda el valor oficial al crear la solicitud.</p><div class="actions"><button [disabled]="busy()||form.invalid||!selected()"><span>{{busy()?'Guardando…':'Crear expediente y continuar'}}</span><m-icon name="arrow"/></button></div></form></section></div>
<section class="journey-note"><span class="count">2</span>Adjuntar documentos <span>→</span><span class="count">3</span>Completar datos <span>→</span><span class="count">4</span>Validar <span>→</span><span class="count">5</span>Analizar</section>
`})
export class NewAnalysisPage {
 auth=inject(AuthService);private api=inject(ApiClient);private router=inject(Router);loading=signal(false);busy=signal(false);error=signal('');clients=signal<Row[]>([]);products=signal<Row[]>([]);branches=signal<Row[]>([]);selected=signal<Row|null>(null);creating=signal(false);searched=signal(false);search='';client:Row={tipoPersona:'NATURAL'};request:Row={numeroSolicitud:'SOL-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+crypto.randomUUID().slice(0,6).toUpperCase(),productoCreditoId:'',sucursalId:''};
 simulando=signal(false);simulacion=signal<Row|null>(null);simulacionError=signal('');
 constructor(){void this.load();}name(c:Row){return c['razonSocial']||[c['nombres'],c['apellidos']].filter(Boolean).join(' ');}
 async simulate(){const id=this.request['productoCreditoId'],monto=Number(this.request['montoSolicitado']),plazo=Number(this.request['plazoSolicitadoMeses']);
  this.simulacion.set(null);this.simulacionError.set('');
  if(!id||!(monto>0)||!(plazo>0))return;
  this.simulando.set(true);
  try{this.simulacion.set(await firstValueFrom(this.api.post<Row>('/productos/'+id+'/simular',{montoSolicitado:monto,plazoMeses:plazo})));}
  catch(e){this.simulacionError.set(errorMessage(e));}
  finally{this.simulando.set(false);}}
 async load(){this.loading.set(true);try{this.products.set(await firstValueFrom(this.api.get<Row[]>('/productos')));this.branches.set(await firstValueFrom(this.api.get<Row[]>('/organizacion/sucursales')));this.request['sucursalId']=this.auth.session()?.identity.membership.sucursalPredeterminadaId||(this.branches().length===1?this.branches()[0]['sucursalId']:'');}catch(e){this.error.set(errorMessage(e));}finally{this.loading.set(false);}}
 async run(fn:()=>Promise<void>){if(this.busy())return;this.busy.set(true);this.error.set('');try{await fn();}catch(e){this.error.set(errorMessage(e));}finally{this.busy.set(false);}}
 async find(){await this.run(async()=>{this.clients.set((await firstValueFrom(this.api.get<{items:Row[]}>('/clientes?size=20&search='+encodeURIComponent(this.search)))).items.filter(x=>x['estado']==='ACTIVO'));this.searched.set(true);});}
 async createClient(){await this.run(async()=>{this.selected.set(await firstValueFrom(this.api.post<Row>('/clientes',this.client)));this.creating.set(false);});}
 async save(){await this.run(async()=>{const created=await firstValueFrom(this.api.post<Row>('/solicitudes',{...this.request,clienteId:this.selected()!['clienteId']}));await this.router.navigate(['/solicitudes',created['solicitudCreditoId'],'expediente'],{queryParams:{paso:1}});});}
}
