import {Component,Input,Output,EventEmitter} from '@angular/core';
import {FormsModule} from '@angular/forms';
export interface RuleNode {operador:string;campo?:string;valor?:number|boolean|string;comparar_con?:string;condiciones?:RuleNode[];}
export const riskFields=[['ingreso_mensual','Ingreso mensual'],['gastos_mensuales','Gastos mensuales'],['ingreso_disponible','Ingreso disponible'],['factor_capacidad','Factor de capacidad'],['capacidad_nueva_cuota','Capacidad de nueva cuota'],['deuda_total_actual','Deuda actual'],['cuotas_actuales','Cuotas actuales'],['cuota_estimada','Cuota propuesta'],['cuota_compatible','Cuota compatible'],['ratio_actual','Ratio actual'],['ratio_post','Ratio posterior'],['monto_solicitado','Monto solicitado'],['plazo_meses','Plazo en meses'],['max_dias_mora_historico','Mora histórica máxima'],['creditos_activos','Créditos activos'],['antiguedad_actividad_meses','Antigüedad de actividad'],['deuda_sobre_ingreso','Deuda / ingreso'],['cuota_sobre_ingreso','Cuota / ingreso'],['monto_sobre_ingreso','Monto / ingreso']];
export function newCondition():RuleNode{return {campo:'cuota_estimada',operador:'>',comparar_con:'capacidad_nueva_cuota'};}
@Component({selector:'rule-builder',imports:[FormsModule],template:`
@if(node.condiciones){<div class="rule-group"><div class="toolbar"><label>Se cumple<select [(ngModel)]="node.operador"><option value="AND">Todas las condiciones</option><option value="OR">Alguna condición</option></select></label><button type="button" class="secondary compact" (click)="add(false)">+ Condición</button><button type="button" class="secondary compact" (click)="add(true)">+ Grupo</button></div>@for(child of node.condiciones;track $index){<div class="rule-child"><rule-builder [node]="child"/><button type="button" class="icon-button danger-text" aria-label="Quitar condición" (click)="node.condiciones.splice($index,1)">×</button></div>}</div>}
@else{<div class="rule-condition"><label>Dato<select [(ngModel)]="node.campo" (ngModelChange)="changeField()">@for(field of fields;track field[0]){<option [value]="field[0]">{{field[1]}}</option>}</select></label><label>Comparación<select [(ngModel)]="node.operador">@for(op of operators;track op){<option [value]="op">{{op}}</option>}</select></label><label>Comparar con<select [ngModel]="node.comparar_con!==undefined?'campo':'valor'" (ngModelChange)="mode($event)"><option value="campo">Otro dato</option><option value="valor">Valor fijo</option></select></label>@if(node.comparar_con!==undefined){<label>Dato comparativo<select [(ngModel)]="node.comparar_con">@for(field of fields;track field[0]){<option [value]="field[0]">{{field[1]}}</option>}</select></label>}@else if(node.campo==='cuota_compatible'){<label>Valor<select [(ngModel)]="node.valor"><option [ngValue]="true">Sí</option><option [ngValue]="false">No</option></select></label>}@else{<label>Valor<input type="number" step="any" [(ngModel)]="node.valor"></label>}</div>}
`})
export class RuleBuilder {
 @Input({required:true}) node!:RuleNode;fields=riskFields;operators=['=','!=','>','>=','<','<='];
 add(group:boolean){this.node.condiciones!.push(group?{operador:'AND',condiciones:[newCondition()]}:newCondition());}
 mode(value:string){if(value==='campo'){delete this.node.valor;this.node.comparar_con='capacidad_nueva_cuota';}else{delete this.node.comparar_con;this.node.valor=this.node.campo==='cuota_compatible'?true:0;}}
 changeField(){if(this.node.campo==='cuota_compatible'){this.node.operador='=';delete this.node.comparar_con;this.node.valor=true;}}
}
