import {Component,inject,signal} from '@angular/core';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {DecimalPipe,DatePipe,PercentPipe} from '@angular/common';
import {firstValueFrom} from 'rxjs';
import {ApiClient,errorMessage} from '../../core/api';
import {AuthService} from '../../core/auth';
import {DialogService} from '../../shared/dialog';
import {LoadingOverlayService} from '../../shared/loading-overlay';
import {Icon} from '../../shared/icon';
import {AlertFocus} from '../../shared/alert-focus';
import {exportCsv} from '../../shared/export-csv';
type Row=Record<string,any>;
@Component({selector:'mapan-analysis',imports:[RouterLink,DecimalPipe,DatePipe,PercentPipe,Icon,AlertFocus],template:`
<header class="page-heading"><div><span class="eyebrow">RIESGO / {{id?'RESULTADO':'ANÁLISIS'}}</span><h1>{{id?'Una visión clara para decidir':'Análisis de crédito'}}</h1><p>{{id?'Resultados conservados de esta ejecución. La decisión final es humana.':'Consulta ejecuciones y retoma la revisión de cada operación.'}}</p></div>@if(!id&&auth.can('Solicitudes:Create')){<a class="primary-link" routerLink="/nuevo-analisis"><m-icon name="plus"/>Nuevo análisis</a>}</header>
@if(error()){<div role="alert" class="error" mapanAlertFocus>{{error()}} <button class="secondary" (click)="load()">Reintentar</button></div>}@if(loading()){<div class="loading-block" role="status">Preparando resultados…</div>}
@if(!id){<section class="panel">@if(!loading()&&!items().length){<div class="empty-state"><m-icon name="chart"/><h2>Aún no hay análisis</h2><p>Completa un expediente y ejecuta su análisis para verlo aquí.</p></div>}@else{<div class="toolbar"><button class="ghost compact" (click)="exportar()"><m-icon name="download"/>Excel</button></div><div class="table-scroll"><table><thead><tr><th>Cliente y solicitud</th><th>Ejecución</th><th>Fecha</th><th>Resultado</th><th></th></tr></thead><tbody>@for(item of items();track item['analisisId']){<tr><td><strong>{{item['cliente']}}</strong><small>{{item['solicitud']}}</small></td><td>#{{item['numeroEjecucion']}}</td><td>{{item['fecha'] | date:'dd/MM/yyyy HH:mm'}}</td><td><span class="badge" [attr.data-state]="item['estado']">{{label(item['recomendacion'] || item['estado'])}}</span></td><td><a class="text-action" [routerLink]="['/analisis',item['analisisId']]">Ver resultado <m-icon name="arrow"/></a></td></tr>}</tbody></table></div>}</section>}
@if(detail();as d){
<section class="case-banner"><div><span class="eyebrow">{{context()['solicitud'] || 'Ejecución histórica'}} · #{{d['analisis']['numeroEjecucion']}}</span><h2>{{context()['cliente']}}</h2><p>{{context()['producto']}} · {{context()['monto'] | number:'1.2-2'}} {{context()['moneda']}} · {{context()['plazo']}} meses</p></div><div><span class="badge" [attr.data-state]="d['analisis']['estado']">{{d['analisis']['estado']}}</span><small>{{d['analisis']['iniciadoEn'] | date:'dd/MM/yyyy HH:mm'}}</small></div></section>
@if(d['snapshot'];as s){<div class="result-grid"><section class="panel"><div class="section-title"><span class="icon-tile"><m-icon name="chart"/></span><h2>Capacidad de pago</h2></div><div class="capacity-value"><strong>{{s['cuotaNuevaEstimada'] | number:'1.2-2'}}</strong><span> / {{s['capacidadNuevaCuota'] | number:'1.2-2'}} {{context()['moneda']}}</span></div><p>Cuota propuesta / capacidad disponible</p><div class="capacity-track" role="meter" aria-label="Uso de la capacidad" [attr.aria-valuenow]="usage()" aria-valuemin="0" aria-valuemax="100"><div [style.width.%]="usage()" [class.over]="!s['cuotaCompatible']"></div></div><span class="badge" [attr.data-state]="s['cuotaCompatible']?'VERDE':'ROJO'">{{s['cuotaCompatible']?'Cuota compatible':'Cuota supera capacidad'}}</span><dl class="metric-list"><dt>Ingreso mensual</dt><dd>{{s['ingresoTotalMensual'] | number:'1.2-2'}}</dd><dt>Gastos mensuales</dt><dd>{{s['gastoTotalMensual'] | number:'1.2-2'}}</dd><dt>Disponible</dt><dd>{{s['ingresoDisponible'] | number:'1.2-2'}}</dd><dt>Factor aplicado</dt><dd>{{s['factorCapacidad'] | percent:'1.0-4'}}</dd></dl></section>
<section class="panel"><div class="section-title"><span class="icon-tile"><m-icon name="loan"/></span><h2>Endeudamiento</h2></div><dl class="metric-list"><dt>Deuda total</dt><dd>{{s['deudaTotalActual'] | number:'1.2-2'}}</dd><dt>Cuotas actuales</dt><dd>{{s['cuotasActuales'] | number:'1.2-2'}}</dd><dt>Ratio actual</dt><dd>{{s['ratioEndeudamientoActual']===null?'Sin ingreso para calcular':(s['ratioEndeudamientoActual'] | percent:'1.1-2')}}</dd><dt>Ratio posterior</dt><dd>{{s['ratioEndeudamientoPost']===null?'Sin ingreso para calcular':(s['ratioEndeudamientoPost'] | percent:'1.1-2')}}</dd></dl><div class="inline-note"><m-icon name="shield"/><span>Política {{context()['politica']}} · versión {{context()['versionPolitica']}}. Cálculos conservados al ejecutar.</span></div>
@if(d['obligaciones']?.length){<h3>Obligaciones declaradas</h3><div class="table-scroll"><table><thead><tr><th>Institución</th><th>Tipo</th><th>Saldo</th><th>Cuota</th><th>Mora</th><th>Estado</th></tr></thead><tbody>@for(o of d['obligaciones'];track $index){<tr><td>{{o['institucion']||'Sin dato'}}</td><td>{{o['tipoObligacion']||'Sin dato'}}</td><td>{{o['saldoActual'] | number:'1.2-2'}}</td><td>{{o['cuotaMensual'] | number:'1.2-2'}}</td><td>{{o['diasMoraActual']}} días</td><td><span class="badge" [attr.data-state]="o['estado']==='VIGENTE'?'VERDE':o['estado']==='REESTRUCTURADA'?'AMARILLO':'INFO'">{{o['estado']}}</span></td></tr>}</tbody></table></div>}</section></div>
<section class="panel"><div class="section-title"><m-icon name="alert"/><h2>Alertas y puntos de atención</h2><span class="count">{{d['alertas'].length}}</span></div>@for(a of d['alertas'];track a['alertaId']){<div class="alert-row" [attr.data-level]="a['nivel']"><div><span class="badge" [attr.data-state]="a['nivel']">{{a['nivel']}}</span><h3>{{a['titulo']}}</h3><p>{{a['descripcion']}}</p><small>Fuente: {{a['codigo']}} · {{a['resuelta']?'Resuelta':'Pendiente de revisión'}}</small></div>@if(!a['resuelta']&&auth.can('Analisis:Execute')){<button class="secondary" [disabled]="busy()" (click)="resolve(a['alertaId'])"><m-icon name="check"/>Marcar revisada</button>}</div>}@empty{<p class="success">No se activaron alertas en esta ejecución.</p>}</section>
@if(context()['reglas']?.length){<section class="panel"><div class="section-title"><m-icon name="shield"/><h2>Reglas evaluadas</h2></div><div class="table-scroll"><table><thead><tr><th>Regla</th><th>Severidad</th><th>Aplicó</th><th>Resultado</th></tr></thead><tbody>@for(rule of context()['reglas'];track $index){<tr><td>{{rule['nombre']}}</td><td><span class="badge" [attr.data-state]="rule['severidad']">{{rule['severidad']}}</span></td><td>{{rule['aplica']?'Sí':'No'}}</td><td>{{rule['aplica']?label(rule['resultado']):'—'}}</td></tr>}</tbody></table></div></section>}
<section class="panel"><div class="section-title"><m-icon name="search"/><h2>Investigación, verificación y visita</h2></div><p class="hint">Lo que ya se sabía del cliente antes de este análisis — capturado tal como estaba en ese momento, no se actualiza si se vuelve a consultar después.</p><dl class="metric-list">
<dt>Score de buró</dt><dd>{{context()['scoreBuro'] ?? 'Sin dato'}}</dd>
<dt>Mora actual (buró)</dt><dd>{{context()['moraActualMaxDiasBuro']!=null?context()['moraActualMaxDiasBuro']+' días':'Sin dato'}}</dd>
<dt>Procesos judiciales</dt><dd>{{context()['tieneProcesosJudiciales']==null?'Sin dato':(context()['tieneProcesosJudiciales']?('Sí — gravedad '+context()['gravedadJudicial']):'No')}}</dd>
<dt>Documentos sospechosos/inconsistentes</dt><dd>{{context()['documentosSospechosos'] ?? 0}}</dd>
<dt>Visita de negocio</dt><dd>{{context()['visitaRecomendacion'] ?? 'No se registró ninguna visita'}}</dd>
</dl></section>
@if(d['documentos'];as docs){<section class="panel"><div class="section-title"><m-icon name="folder"/><h2>Documentos</h2><span class="count">{{docs.length}}</span></div>@if(docs.length){<div class="table-scroll"><table><thead><tr><th>Tipo</th><th>Archivo</th><th>Versión</th><th>Obligatorio</th><th>Estado</th></tr></thead><tbody>@for(doc of docs;track $index){<tr><td>{{doc['tipoDocumento']}}</td><td>{{doc['nombreArchivo']}}</td><td>{{doc['numeroVersion']}}</td><td>{{doc['obligatorio']?'Sí':'No'}}</td><td><span class="badge" [attr.data-state]="doc['estadoAsociacion']==='VALIDADO'?'VERDE':doc['estadoAsociacion']==='RECHAZADO'?'ROJO':'INFO'">{{doc['estadoAsociacion']}}</span></td></tr>}</tbody></table></div>}@else{<p>Sin documentos asociados a esta solicitud.</p>}</section>}
<section class="panel model-status"><span class="icon-tile"><m-icon name="model"/></span><div><h2>Modelo predictivo</h2><p>{{label(context()['mlStatus'])}}</p>@if(d['prediccion'];as p){<p>Probabilidad de incumplimiento: {{p['probabilidadIncumplimiento'] | percent:'1.2-2'}} · {{p['nivelRiesgo']}} · versión {{context()['versionModelo']}}</p>}
@if(context()['resumenRiesgo']){<p class="hint"><m-icon name="alert"/>{{context()['resumenRiesgo']}}</p>}
@if(context()['sugerenciasRiesgo']?.length){<div class="model-suggestions"><h4><m-icon name="model"/>Sugerencias para la cooperativa</h4><ul>@for(s of context()['sugerenciasRiesgo'];track $index){<li><m-icon name="check"/><span>{{s}}</span></li>}</ul></div>}
</div></section>
<section class="recommendation"><span class="eyebrow">RECOMENDACIÓN DEL SISTEMA</span><h2>{{label(d['recomendacion']['codigoRecomendacion'])}}</h2><p>{{d['recomendacion']['resumen']}}</p><div class="inline-note"><m-icon name="shield"/>Requiere revisión humana. Este resultado no aprueba ni rechaza el crédito.</div>
@if(auth.can('Solicitudes:Decidir')&&d['analisis']['estado']==='COMPLETADO'){<div class="actions"><button (click)="decide('APROBAR')"><m-icon name="check"/>Aprobar solicitud</button><button class="secondary" (click)="decide('RECHAZAR')"><m-icon name="x"/>Rechazar solicitud</button></div><p class="hint">Solo funciona si esta solicitud no tiene un flujo de aprobación configurado — si lo tiene, decide desde la bandeja de aprobaciones.</p>}</section>
<div class="sticky-actions"><a class="secondary button-link" [routerLink]="['/solicitudes',d['analisis']['solicitudCreditoId'],'expediente']"><m-icon name="back"/>Volver al expediente</a><button [disabled]="busy()" (click)="viewReport()"><m-icon name="download"/>Ver informe (PDF)</button></div>
} @else {<section class="panel"><h2>La ejecución no se completó</h2><p>Los datos parciales se descartaron. Revisa el expediente y la configuración antes de intentar nuevamente.</p><a [routerLink]="['/solicitudes',d['analisis']['solicitudCreditoId'],'expediente']">Volver al expediente</a></section>}}
`})
export class AnalysisPage {
 auth=inject(AuthService);private api=inject(ApiClient);private dialog=inject(DialogService);private loadingOverlay=inject(LoadingOverlayService);id=inject(ActivatedRoute).snapshot.paramMap.get('id');items=signal<Row[]>([]);detail=signal<Row|null>(null);error=signal('');loading=signal(false);busy=signal(false);
 constructor(){void this.load();}context():Row{return this.detail()?.['contexto']||{};}
 label(value:string){const names:Record<string,string>={CAPACIDAD_COMPATIBLE:'Capacidad compatible',CAPACIDAD_NO_COMPATIBLE:'Capacidad no compatible',REVISION_ADICIONAL:'Revisión adicional',MODELO_PREDICTIVO_NO_CONFIGURADO:'Modelo predictivo no configurado',MODELO_PREDICTIVO_NO_DISPONIBLE:'Modelo temporalmente no disponible',CONFIGURACION_ML_AMBIGUA:'Revisar configuración del modelo',CONFIGURADO:'Modelo propio (ml-service)',CONFIGURADO_CLAUDE_TEMPORAL:'Respaldo temporal con IA (Claude) — el modelo propio aún no está entrenado'};return names[value]||value||'Sin resultado';}
 usage(){const s=this.detail()?.['snapshot'];return s?Math.min(100,Math.max(0,s['capacidadNuevaCuota']>0?s['cuotaNuevaEstimada']/s['capacidadNuevaCuota']*100:100)):0;}
 exportar(){exportCsv('analisis',[{key:'cliente',label:'Cliente'},{key:'solicitud',label:'Solicitud'},{key:'numeroEjecucion',label:'Ejecución'},{key:'fecha',label:'Fecha'},{key:'estado',label:'Estado'},{key:'recomendacion',label:'Recomendación'}],this.items());}
 async load(){this.loading.set(true);this.error.set('');try{if(this.id)this.detail.set(await firstValueFrom(this.api.get<Row>('/analisis/'+this.id)));else this.items.set(await firstValueFrom(this.api.get<Row[]>('/analisis')));}catch(e){this.error.set(errorMessage(e));}finally{this.loading.set(false);}}
 async viewReport(){this.busy.set(true);this.loadingOverlay.show('Generando informe…');try{const blob=await firstValueFrom(this.api.download('/analisis/'+this.id+'/informe'));const url=URL.createObjectURL(new Blob([blob],{type:'application/pdf'}));window.open(url,'_blank');}catch(e){this.error.set(errorMessage(e));}finally{this.busy.set(false);this.loadingOverlay.hide();}}
 async resolve(id:string){if(!await this.dialog.confirm('¿Confirmas que revisaste esta alerta? La recomendación histórica se conserva.',{title:'Marcar alerta como revisada'}))return;this.busy.set(true);this.loadingOverlay.show('Guardando…');try{await firstValueFrom(this.api.post('/alertas/'+id+'/resolver',{}));await this.load();}catch(e){this.error.set(errorMessage(e));}finally{this.busy.set(false);this.loadingOverlay.hide();}}
 async decide(decision:string){
  const comentario=await this.dialog.prompt(decision==='APROBAR'?'Comentario de aprobación (opcional):':'Motivo del rechazo (opcional):',{title:decision==='APROBAR'?'Aprobar solicitud':'Rechazar solicitud'});
  if(comentario===null)return;
  if(!await this.dialog.confirm('¿Confirmas esta decisión? Cierra la solicitud de forma definitiva.',{title:decision==='APROBAR'?'Aprobar solicitud':'Rechazar solicitud',tone:decision==='APROBAR'?undefined:'danger'}))return;
  this.busy.set(true);this.loadingOverlay.show('Registrando decisión…');try{await firstValueFrom(this.api.post('/analisis/'+this.id+'/decision',{decision,comentario:comentario||null}));await this.load();}catch(e){this.error.set(errorMessage(e));}finally{this.busy.set(false);this.loadingOverlay.hide();}
 }
}
