import {Component,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {DatePipe} from '@angular/common';
import {firstValueFrom} from 'rxjs';
import {ApiClient,errorMessage} from '../../core/api';
import {AuthService} from '../../core/auth';
import {DialogService} from '../../shared/dialog';
import {Icon} from '../../shared/icon';
import {RuleBuilder,RuleNode,newCondition} from '../../shared/rule-builder';
import {AlertFocus} from '../../shared/alert-focus';
type Row=Record<string,any>;
@Component({selector:'mapan-policies',imports:[FormsModule,DatePipe,Icon,RuleBuilder,AlertFocus],template:`
<header class="page-heading"><div><span class="eyebrow">RIESGO / POLÍTICAS</span><h1>Políticas de crédito</h1><p>Define criterios claros y conserva el historial de cada versión.</p></div>@if(canManage()){<button (click)="policyForm.set({estado:'ACTIVA'})"><m-icon name="plus"/>Nueva política</button>}</header>
@if(error()){<div class="error" role="alert" mapanAlertFocus>{{error()}} <button class="secondary" (click)="load()">Reintentar</button></div>}@if(success()){<p class="success" role="status">{{success()}}</p>}@if(loading()){<p role="status" class="loading-block">Cargando políticas…</p>}
@if(policyForm();as p){<section class="panel"><h2>{{p['politicaCreditoId']?'Editar política':'Nueva política'}}</h2><form (ngSubmit)="savePolicy()" #pf="ngForm"><div class="grid-form"><label>Código<input name="code" [(ngModel)]="p['codigo']" maxlength="60" required></label><label>Nombre<input name="name" [(ngModel)]="p['nombre']" maxlength="180" required></label><label>Producto<select name="product" [(ngModel)]="p['productoCreditoId']"><option [ngValue]="null">Todos los productos de la empresa</option>@for(product of products();track product['productoCreditoId']){<option [value]="product['productoCreditoId']">{{product['nombre']}}</option>}</select></label><label>Estado<select name="state" [(ngModel)]="p['estado']"><option>ACTIVA</option><option>INACTIVA</option></select></label><label>Descripción<textarea name="description" [(ngModel)]="p['descripcion']"></textarea></label></div><div class="actions"><button [disabled]="busy()||pf.invalid"><m-icon name="check"/>Guardar política</button><button type="button" class="secondary" (click)="policyForm.set(null)">Cancelar</button></div></form></section>}
<div class="policy-layout"><section class="panel"><h2>Políticas de la empresa</h2>@for(p of policies();track p['politicaCreditoId']){<button class="select-row" [class.selected]="selectedPolicy()?.['politica']['politicaCreditoId']===p['politicaCreditoId']" (click)="selectPolicy(p['politicaCreditoId'])"><span><strong>{{p['nombre']}}</strong><small>{{p['codigo']}} · {{p['estado']}}</small></span><m-icon name="arrow"/></button>}@empty{<div class="empty-state"><m-icon name="shield"/><p>Aún no hay políticas configuradas.</p></div>}</section>
<div>@if(selectedPolicy();as p){<section class="panel"><div class="section-title"><h2>{{p['politica']['nombre']}}</h2>@if(canManage()){<button class="secondary compact" (click)="policyForm.set({...p['politica']})">Editar</button>}</div><p>Las versiones publicadas conservan sus parámetros y reglas. Los cambios se preparan en un nuevo borrador.</p><div class="version-list">@for(v of p['versiones'];track v['politicaVersionId']){<button class="select-row" [class.selected]="version()?.['version']['politicaVersionId']===v['politicaVersionId']" (click)="selectVersion(v['politicaVersionId'])"><strong>Versión {{v['numeroVersion']}}</strong><span>{{v['vigenteDesde'] | date:'dd/MM/yyyy'}}</span><span class="badge" [attr.data-state]="v['estado']">{{v['estado']}}</span></button>}</div>@if(canManage()){<div class="toolbar"><label>Inicio de la nueva versión<input type="date" [(ngModel)]="startDate"></label><button class="secondary" [disabled]="busy()||!startDate" (click)="newVersion()"><m-icon name="plus"/>Crear borrador</button></div>}</section>}
@if(version();as v){<section class="panel"><div class="section-title"><h2>Versión {{v['version']['numeroVersion']}}</h2><span class="badge" [attr.data-state]="v['version']['estado']">{{v['version']['estado']}}</span></div>@if(!v['editable']){<p class="inline-note"><m-icon name="shield"/>Contenido protegido. Crea un nuevo borrador para modificarlo.</p>}@if(canManage()&&v['version']['estado']!=='ARCHIVADA'){<div class="actions">@if(v['version']['estado']!=='VIGENTE'){<button [disabled]="busy()" (click)="state('VIGENTE')">Publicar versión</button>}<button class="secondary" [disabled]="busy()" (click)="state('INACTIVA')">Inactivar</button><button class="secondary" [disabled]="busy()" (click)="state('ARCHIVADA')">Archivar</button></div>}
<h3>Parámetros</h3>@for(p of v['parametros'];track p['parametroId']){<div class="list-row"><div><strong>{{p['nombre']}}</strong><small>{{p['codigo']}} · {{p['tipoDato']}}</small><p>{{parameterValue(p)}}</p></div>@if(editable()){<div class="actions"><button class="secondary compact" (click)="editParameter(p)">Editar</button><button class="ghost compact danger-text" (click)="remove('parametros',p['parametroId'])">Eliminar</button></div>}</div>}@empty{<p>Agrega los parámetros que necesita esta política.</p>}@if(editable()){<button class="secondary" (click)="editParameter(null)"><m-icon name="plus"/>Agregar parámetro</button>}
@if(parameter();as p){<form (ngSubmit)="saveParameter()" #param="ngForm" class="editor-surface"><div class="grid-form"><label>Código<input name="code" [(ngModel)]="p['codigo']" required maxlength="100"></label><label>Nombre<input name="name" [(ngModel)]="p['nombre']" required maxlength="180"></label><label>Tipo<select name="type" [(ngModel)]="p['tipoDato']" (ngModelChange)="parameterInput=''">@for(type of types;track type){<option>{{type}}</option>}</select></label><label>Valor@switch(p['tipoDato']){@case('BOOLEANO'){<select name="value" [(ngModel)]="parameterInput"><option [ngValue]="true">Sí</option><option [ngValue]="false">No</option></select>}@case('JSON'){<textarea name="value" [(ngModel)]="parameterInput" required rows="4"></textarea>}@default{<input name="value" [(ngModel)]="parameterInput" [type]="p['tipoDato']==='NUMERO'?'number':p['tipoDato']==='FECHA'?'date':'text'" step="any" required>}}</label></div><div class="actions"><button [disabled]="busy()||param.invalid">Guardar parámetro</button><button type="button" class="secondary" (click)="parameter.set(null)">Cancelar</button></div></form>}
<h3>Reglas de evaluación</h3><p class="hint">Preevaluación: se evalúa justo después de investigar al cliente, antes de pedir documentos. Análisis: se evalúa junto con la capacidad de pago, al final.</p>@for(r of v['reglas'];track r['reglaId']){<div class="list-row"><div><strong>{{r['nombre']}}</strong><small>{{r['etapa']==='PREEVALUACION'?'Preevaluación':'Análisis'}} · Prioridad {{r['prioridad']}} · {{r['activa']?'Activa':'Inactiva'}}</small><span class="badge" [attr.data-state]="r['severidad']">{{r['severidad']}}</span></div>@if(editable()){<div class="actions"><button class="secondary compact" (click)="editRule(r)">Editar regla</button><button class="ghost compact danger-text" (click)="remove('reglas',r['reglaId'])">Eliminar</button></div>}</div>}@empty{<p>Sin reglas. Se recomendará según compatibilidad de cuota, siempre con revisión humana.</p>}@if(editable()){<button class="secondary" (click)="editRule(null)"><m-icon name="plus"/>Crear regla visual</button>}
</section>}
</div></div>
@if(rule();as r){<section class="panel rule-editor"><span class="eyebrow">CONSTRUCTOR DE REGLAS</span><h2>{{r['reglaId']?'Editar regla':'Nueva regla'}}</h2><div class="grid-form"><label>Código<input [(ngModel)]="r['codigo']" maxlength="100"></label><label>Nombre<input [(ngModel)]="r['nombre']" maxlength="180"></label><label>Descripción<input [(ngModel)]="r['descripcion']"></label><label>Prioridad (menor número primero)<input type="number" [(ngModel)]="r['prioridad']"></label>
<label>Etapa<select [(ngModel)]="r['etapa']" (ngModelChange)="onEtapaChange(r)"><option value="PREEVALUACION">Preevaluación (buró, judicial, aval)</option><option value="ANALISIS">Análisis financiero</option></select></label></div>
<h3>Cuando se cumpla</h3><rule-builder [node]="condition"/>
@if(r['etapa']==='PREEVALUACION'){<p class="hint">Campos disponibles: score_buro, score_buro_disponible, banda_riesgo_buro, deuda_total_buro, cuota_total_buro, operaciones_vencidas_buro, max_dias_vencido_3_meses_buro, monto_demanda_judicial_buro, monto_cartera_castigada_buro, mora_actual_max_dias_buro, mora_actual_disponible_buro, judicial_disponible, tiene_procesos_judiciales, numero_procesos_judiciales, gravedad_judicial, aval_disponible, es_garante_activo, tiene_mora_como_garante, operaciones_como_garante, monto_solicitado, plazo_solicitado_meses.</p>}
@else if(r['etapa']==='ANALISIS'){<p class="hint">Campos disponibles: ingreso_mensual, gastos_mensuales, ingreso_disponible, factor_capacidad, capacidad_nueva_cuota, deuda_total_actual, cuotas_actuales, cuota_estimada, cuota_compatible, ratio_actual, ratio_post, monto_solicitado, plazo_meses, max_dias_mora_historico, creditos_activos, antiguedad_actividad_meses, deuda_sobre_ingreso, cuota_sobre_ingreso, monto_sobre_ingreso, score_buro, score_buro_disponible, mora_actual_max_dias_buro, mora_actual_disponible_buro, tiene_procesos_judiciales, judicial_disponible, gravedad_judicial, documentos_sospechosos, visita_recomendacion, visita_disponible.</p>}
<div class="grid-form"><label>Severidad<select [(ngModel)]="r['severidad']">@for(s of severities;track s){<option>{{s}}</option>}</select></label>
<label>Resultado<select [(ngModel)]="r['resultado']">
@if(r['etapa']==='PREEVALUACION'){<option value="CONTINUAR">Continuar</option><option value="ALERTA">Alerta (no bloquea)</option><option value="REQUIERE_EXCEPCION">Requiere excepción</option><option value="BLOQUEAR">Bloquear (hard stop)</option>}
@else{<option value="CAPACIDAD_COMPATIBLE">Capacidad compatible</option><option value="CAPACIDAD_NO_COMPATIBLE">Capacidad no compatible</option><option value="REVISION_ADICIONAL">Revisión adicional</option>}
</select></label><label class="check-row"><input type="checkbox" [(ngModel)]="r['activa']">Regla activa</label></div>@if(auth.can('Seguridad:Manage')){<details><summary>Ver JSON avanzado</summary><pre>{{jsonCondition()}}</pre></details>}<div class="actions"><button [disabled]="busy()||!r['codigo']||!r['nombre']" (click)="saveRule()"><m-icon name="check"/>Guardar regla</button><button class="secondary" (click)="rule.set(null)">Cancelar</button></div></section>}
`})
export class PoliciesPage {
 auth=inject(AuthService);private api=inject(ApiClient);private dialog=inject(DialogService);policies=signal<Row[]>([]);products=signal<Row[]>([]);selectedPolicy=signal<Row|null>(null);version=signal<Row|null>(null);policyForm=signal<Row|null>(null);parameter=signal<Row|null>(null);rule=signal<Row|null>(null);error=signal('');success=signal('');loading=signal(false);busy=signal(false);startDate=new Date().toISOString().slice(0,10);parameterInput:any='';types=['NUMERO','BOOLEANO','FECHA','TEXTO','JSON'];severities=['INFO','VERDE','AMARILLO','ROJO'];condition:RuleNode={operador:'AND',condiciones:[newCondition()]};
 constructor(){void this.load();}canManage(){return this.auth.can('Politicas:Manage');}editable(){return this.canManage()&&this.version()?.['editable'];}jsonCondition(){return JSON.stringify(this.condition,null,2);}
 async load(){this.loading.set(true);try{this.policies.set(await firstValueFrom(this.api.get<Row[]>('/politicas')));if(this.auth.can('Productos:Read'))this.products.set(await firstValueFrom(this.api.get<Row[]>('/productos')));}catch(e){this.error.set(errorMessage(e));}finally{this.loading.set(false);}}
 async run(action:()=>Promise<void>){if(this.busy())return;this.busy.set(true);this.error.set('');this.success.set('');try{await action();this.success.set('Cambios guardados.');}catch(e){this.error.set(errorMessage(e));}finally{this.busy.set(false);}}
 async selectPolicy(id:string){await this.run(async()=>{this.selectedPolicy.set(await firstValueFrom(this.api.get<Row>('/politicas/'+id)));this.version.set(null);this.parameter.set(null);this.rule.set(null);});}
 async selectVersion(id:string){await this.run(async()=>{this.version.set(await firstValueFrom(this.api.get<Row>('/politicas/versiones/'+id)));this.parameter.set(null);this.rule.set(null);});}
 async refreshVersion(){const id=this.version()!['version']['politicaVersionId'];this.version.set(await firstValueFrom(this.api.get<Row>('/politicas/versiones/'+id)));}
 async savePolicy(){await this.run(async()=>{const p=this.policyForm()!;await firstValueFrom(p['politicaCreditoId']?this.api.put('/politicas/'+p['politicaCreditoId'],p):this.api.post('/politicas',p));this.policyForm.set(null);await this.load();});}
 async newVersion(){await this.run(async()=>{const id=this.selectedPolicy()!['politica']['politicaCreditoId'];const v=await firstValueFrom(this.api.post<string>('/politicas/'+id+'/versiones',{vigenteDesde:this.startDate+'T00:00:00Z',vigenteHasta:null}));this.selectedPolicy.set(await firstValueFrom(this.api.get<Row>('/politicas/'+id)));this.version.set(await firstValueFrom(this.api.get<Row>('/politicas/versiones/'+v)));});}
 async state(state:string){if(!await this.dialog.confirm('¿Confirmas cambiar esta versión a '+state+'? El contenido histórico se conserva.',{title:'Cambiar estado de la versión'}))return;await this.run(async()=>{await firstValueFrom(this.api.postRaw('/politicas/versiones/'+this.version()!['version']['politicaVersionId']+'/estado',state));await this.refreshVersion();this.selectedPolicy.set(await firstValueFrom(this.api.get<Row>('/politicas/'+this.selectedPolicy()!['politica']['politicaCreditoId'])));});}
 parameterValue(p:Row){return p['valorNumerico']??p['valorBooleano']??p['valorFecha']??p['valorTexto']??p['valorJson'];}
 editParameter(p:Row|null){this.parameter.set(p?{...p}:{tipoDato:'NUMERO'});this.parameterInput=p?this.parameterValue(p):'';}
 async saveParameter(){await this.run(async()=>{const p=this.parameter()!;const fields:Record<string,string>={NUMERO:'valorNumerico',BOOLEANO:'valorBooleano',FECHA:'valorFecha',TEXTO:'valorTexto',JSON:'valorJson'};const payload:Row={codigo:p['codigo'],nombre:p['nombre'],tipoDato:p['tipoDato']};payload[fields[p['tipoDato']]]=this.parameterInput;const url='/politicas/versiones/'+this.version()!['version']['politicaVersionId']+'/parametros';await firstValueFrom(p['parametroId']?this.api.put(url+'/'+p['parametroId'],payload):this.api.post(url,payload));this.parameter.set(null);await this.refreshVersion();});}
 editRule(r:Row|null){const accion=r?JSON.parse(r['accionJson']):null;this.rule.set(r?{...r,resultado:accion['resultado']??accion['accion']}:{prioridad:100,severidad:'AMARILLO',resultado:'REVISION_ADICIONAL',activa:true,etapa:'ANALISIS'});this.condition=r?JSON.parse(r['condicionJson']):{operador:'AND',condiciones:[newCondition()]};}
 onEtapaChange(r:Row){r['resultado']=r['etapa']==='PREEVALUACION'?'ALERTA':'REVISION_ADICIONAL';}
 async saveRule(){await this.run(async()=>{const r=this.rule()!;const url='/politicas/versiones/'+this.version()!['version']['politicaVersionId']+'/reglas';const payload={...r,condicionJson:JSON.stringify(this.condition)};await firstValueFrom(r['reglaId']?this.api.put(url+'/'+r['reglaId'],payload):this.api.post(url,payload));this.rule.set(null);await this.refreshVersion();});}
 async remove(kind:string,id:string){if(!await this.dialog.confirm('¿Eliminar este elemento del borrador?',{title:'Eliminar',confirmLabel:'Eliminar',tone:'danger'}))return;await this.run(async()=>{await firstValueFrom(this.api.delete('/politicas/versiones/'+this.version()!['version']['politicaVersionId']+'/'+kind+'/'+id));await this.refreshVersion();});}
}
