import {Component,inject,signal} from '@angular/core';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {FormsModule} from '@angular/forms';
import {DatePipe} from '@angular/common';
import {firstValueFrom} from 'rxjs';
import {ApiClient,errorMessage} from '../../core/api';
import {AuthService} from '../../core/auth';
import {DialogService, Modal} from '../../shared/dialog';
import {Icon} from '../../shared/icon';
import {RuleBuilder,RuleNode,newCondition} from '../../shared/rule-builder';
import {AlertFocus} from '../../shared/alert-focus';
import {exportCsv} from '../../shared/export-csv';
import {LoadingOverlayService} from '../../shared/loading-overlay';
type Row=Record<string,any>;
interface Field{key:string;label:string;type?:string;required?:boolean;options?:string[];}
@Component({selector:'mapan-operations',imports:[FormsModule,RouterLink,DatePipe,Icon,RuleBuilder,Modal,AlertFocus],template:`
<header class="page-heading"><div><span class="eyebrow">{{eyebrow}}</span><h1>{{title}}</h1><p>{{subtitle}}</p></div>@if(canManage()&&area!=='workflow'&&area!=='alertas'){<button (click)="create()"><m-icon name="plus"/>{{area==='prestamos'?'Registrar préstamo':area==='desempeno'?'Registrar corte':area==='rutas'?'Nueva ruta':'Configurar proveedor'}}</button>}</header>
@if(error()){<div class="error" role="alert" mapanAlertFocus>{{error()}} <button class="secondary" (click)="load()">Reintentar</button></div>}@if(success()){<p class="success" role="status">{{success()}}</p>}@if(loading()){<p class="loading-block" role="status">Cargando información…</p>}
@if(area==='auditoria'){<section class="panel"><div class="grid-form"><label>Desde<input type="date" [(ngModel)]="filters['desde']"></label><label>Hasta<input type="date" [(ngModel)]="filters['hasta']"></label><label>Entidad<input [(ngModel)]="filters['entidad']" placeholder="Ej. riesgo.analisis"></label><label>Acción<input [(ngModel)]="filters['accion']" placeholder="Ej. EJECUTAR"></label><label>Correlación<input [(ngModel)]="filters['correlationId']" placeholder="Referencia de la operación"></label></div><div class="actions"><button [disabled]="loading()" (click)="page.set(1);load()"><m-icon name="search"/>Aplicar filtros</button><button class="secondary" [disabled]="loading()" (click)="filters={};page.set(1);load()">Limpiar</button></div></section>}
@if(area==='integraciones'){<div class="inline-note"><m-icon name="plug"/>Los proveedores externos requieren un adaptador y credenciales reales. Adjunta sus informes manualmente al expediente.</div>}
@if(area==='desempeno'){<a class="text-action" routerLink="/prestamos"><m-icon name="back"/>Volver a préstamos</a>}
@if(area==='workflow'){<section class="panel">@for(row of items();track row['aprobacionPasoId']){<div class="approval-card"><div><span class="eyebrow">{{row['solicitud']}}</span><h2>{{row['nombrePaso']}}</h2><p>{{row['rol']}} · {{row['cantidadAprobacionesRequeridas']}} aprobación(es) requerida(s)</p><p class="hint"><m-icon name="audit"/>Análisis ejecutado {{row['analisisIniciadoEn'] | date:'dd/MM/yyyy HH:mm'}} · esperando desde {{row['fechaHabilitacion'] | date:'dd/MM/yyyy HH:mm'}}</p><a [routerLink]="['/analisis',row['analisisId']]">Revisar análisis completo</a></div>@if(canManage()){<div class="actions"><button [disabled]="busy()" (click)="decide(row,'APROBAR')"><m-icon name="check"/>Aprobar paso</button><button class="secondary" [disabled]="busy()" (click)="decide(row,'DEVOLVER')"><m-icon name="back"/>Devolver</button><button class="ghost danger-text" [disabled]="busy()" (click)="decide(row,'RECHAZAR')"><m-icon name="x"/>Rechazar</button></div>}</div>}@empty{<div class="empty-state"><m-icon name="check"/><h2>No tienes aprobaciones pendientes</h2><p>Las solicitudes sin ruta aplicable finalizan en recomendación.</p></div>}</section>}
@else{<section class="panel"><div class="section-title"><h2>{{area==='auditoria'?'Historial de actividad':'Registros de la empresa'}}</h2><div class="toolbar"><button class="ghost compact" [disabled]="busy()||loading()" (click)="exportar()"><m-icon name="download"/>Excel</button><button class="ghost compact" [disabled]="loading()" (click)="load()">Actualizar</button></div></div>@if(items().length){<div class="table-scroll"><table><thead><tr>@for(col of columns;track col.key){<th>{{col.label}}</th>}@if(area!=='auditoria'){<th>Acciones</th>}</tr></thead><tbody>@for(row of items();track $index){<tr>@for(col of columns;track col.key){<td>@if(col.key==='estado'||col.key==='nivel'){<span class="badge" [attr.data-state]="row[col.key]">{{row[col.key]}}</span>}@else if(col.type==='date'){ {{row[col.key] | date:'dd/MM/yyyy'}} }@else{ {{display(row[col.key])}} }</td>}@if(area!=='auditoria'){<td>@if(area==='prestamos'){<a class="text-action" [routerLink]="['/prestamos',row['prestamoId']]">Ver cortes <m-icon name="arrow"/></a>}@if(area==='alertas'){<a [routerLink]="['/analisis',row['analisisId']]">Ver análisis</a>}@if(canManage()&&area!=='rutas'&&area!=='alertas'){<button class="ghost compact" (click)="edit(row)">Editar</button>}</td>}</tr>}</tbody></table></div>}@else{<div class="empty-state"><m-icon [name]="area==='auditoria'?'audit':'folder'"/><h2>No hay registros para mostrar</h2><p>{{area==='rutas'?'La empresa funciona sin flujo de aprobación. Puedes configurar uno cuando lo necesites.':'Los registros aparecerán aquí cuando se creen operaciones en la empresa.'}}</p></div>}
@if(area==='auditoria'||area==='prestamos'){<div class="pagination"><button class="secondary compact" [disabled]="page()===1" (click)="page.set(page()-1);load()">Anterior</button><span>Página {{page()}}</span><button class="secondary compact" [disabled]="items().length<size()" (click)="page.set(page()+1);load()">Siguiente</button><label class="page-size">Ver<select [ngModel]="size()" (ngModelChange)="size.set($event);page.set(1);load()"><option [ngValue]="5">5</option><option [ngValue]="10">10</option><option [ngValue]="20">20</option><option [ngValue]="50">50</option></select>registros</label></div>}</section>}
@if(form();as f){<mapan-modal (close)="form.set(null)"><span class="eyebrow">{{editingId?'CORREGIR REGISTRO':'NUEVO REGISTRO'}}</span><h2>{{title}}</h2><form (ngSubmit)="save()" #editor="ngForm"><div class="grid-form">
@for(field of fields;track field.key){<label>{{field.label}}@if(field.options){<select [name]="field.key" [(ngModel)]="f[field.key]" [required]="field.required||false">@for(option of field.options;track option){<option>{{option}}</option>}</select>}@else if(field.type==='checkbox'){<input type="checkbox" [name]="field.key" [(ngModel)]="f[field.key]">}@else{<input [type]="field.type||'text'" [name]="field.key" [(ngModel)]="f[field.key]" [required]="field.required||false" [attr.min]="field.type==='number'?0:null" step="any">}</label>}
@if(area==='prestamos'){<label>Solicitud<select name="request" [(ngModel)]="f['solicitudCreditoId']" required><option value="">Seleccionar solicitud</option>@for(r of requests();track r['solicitudCreditoId']){<option [value]="r['solicitudCreditoId']">{{r['numeroSolicitud']}} · {{r['estado']}}</option>}</select></label><label class="check-row"><input type="checkbox" name="confirm" [(ngModel)]="f['confirmacionHumana']" required>Confirmo que este registro tiene autorización humana. La recomendación no constituye autorización de desembolso.</label>}
@if(area==='integraciones'){<label>Proveedor<select name="provider" [(ngModel)]="f['proveedorId']" required>@for(p of data()['proveedores']||[];track p['proveedorId']){<option [value]="p['proveedorId']">{{p['nombre']}}</option>}</select></label>}
</div>
@if(area==='rutas'){<h3>Pasos de aprobación</h3>@for(step of routeSteps;track $index){<div class="grid-form editor-surface"><label>Nombre del paso<input [name]="'step'+$index" [(ngModel)]="step['nombre']" required></label><label>Rol responsable<select [name]="'role'+$index" [(ngModel)]="step['rolId']" required>@for(role of data()['roles']||[];track role['rolId']){<option [value]="role['rolId']">{{role['nombre']}}</option>}</select></label><label>Aprobaciones requeridas<input type="number" min="1" [name]="'count'+$index" [(ngModel)]="step['cantidadAprobacionesRequeridas']" required></label><button type="button" class="ghost danger-text" (click)="routeSteps.splice($index,1)">Quitar paso</button></div>}<button type="button" class="secondary" (click)="routeSteps.push({cantidadAprobacionesRequeridas:1})">+ Agregar paso</button>@if(!f['esPredeterminada']){<h3>Condición para aplicar esta ruta</h3><rule-builder [node]="condition"/>}}
<div class="actions"><button [disabled]="busy()||editor.invalid"><m-icon name="check"/>Guardar {{area==='desempeno'?'corte':'registro'}}</button><button type="button" class="secondary" (click)="form.set(null)">Cancelar</button></div></form></mapan-modal>}
`})
export class OperationsPage {
 auth=inject(AuthService);private api=inject(ApiClient);private dialog=inject(DialogService);private loadingOverlay=inject(LoadingOverlayService);private route=inject(ActivatedRoute);area=this.route.snapshot.data['area'] as string;loanId=this.route.snapshot.paramMap.get('id');title='';subtitle='';eyebrow='CONTROL';columns:Field[]=[];fields:Field[]=[];permission='';data=signal<Row>({});items=signal<Row[]>([]);requests=signal<Row[]>([]);error=signal('');success=signal('');loading=signal(false);busy=signal(false);form=signal<Row|null>(null);editingId:string|null=null;filters:Record<string,string>={};page=signal(1);size=signal(20);routeSteps:Row[]=[{cantidadAprobacionesRequeridas:1}];condition:RuleNode={operador:'AND',condiciones:[newCondition()]};
 constructor(){const configs:Record<string,{title:string;permission:string;columns:Field[];fields?:Field[]}>={
 auditoria:{title:'Auditoría',permission:'Auditoria',columns:[{key:'fechaEvento',label:'Fecha',type:'date'},{key:'usuario',label:'Usuario'},{key:'entidadTipo',label:'Entidad'},{key:'accion',label:'Acción'},{key:'exitoso',label:'Correcto'},{key:'correlationId',label:'Correlación'}]},
 alertas:{title:'Alertas',permission:'Alertas',columns:[{key:'titulo',label:'Punto de atención'},{key:'nivel',label:'Severidad'},{key:'resuelta',label:'Revisada'}]},
 prestamos:{title:'Préstamos',permission:'Prestamos',columns:[{key:'numeroPrestamo',label:'Préstamo'},{key:'solicitud',label:'Solicitud'},{key:'sucursal',label:'Sucursal'},{key:'fechaDesembolso',label:'Desembolso',type:'date'},{key:'montoDesembolsado',label:'Monto'},{key:'cuotaPactada',label:'Cuota'},{key:'estado',label:'Estado'}],fields:[{key:'numeroPrestamo',label:'Número de préstamo',required:true},{key:'montoDesembolsado',label:'Monto desembolsado',type:'number',required:true},{key:'plazoMeses',label:'Plazo en meses',type:'number',required:true},{key:'cuotaPactada',label:'Cuota pactada',type:'number',required:true},{key:'fechaDesembolso',label:'Fecha de desembolso',type:'date',required:true},{key:'estado',label:'Estado',options:['VIGENTE','LIQUIDADO','VENCIDO','REESTRUCTURADO','CASTIGADO','CANCELADO'],required:true}]},
 desempeno:{title:'Historial de desempeño',permission:'Prestamos',columns:[{key:'fechaCorte',label:'Corte',type:'date'},{key:'saldoCapital',label:'Saldo'},{key:'montoPagadoPeriodo',label:'Pago'},{key:'diasMora',label:'Días de mora'},{key:'mora15',label:'Mora 15'},{key:'mora30',label:'Mora 30'},{key:'mora60',label:'Mora 60'},{key:'mora90',label:'Mora 90'},{key:'reestructurado',label:'Reestructurado'},{key:'refinanciado',label:'Refinanciado'},{key:'castigado',label:'Castigado'}],fields:[{key:'fechaCorte',label:'Fecha de corte',type:'date',required:true},...['saldoCapital','cuotaExigible','montoPagadoPeriodo','diasMora'].map((key,i)=>({key,label:['Saldo de capital','Cuota exigible','Monto pagado en el período','Días de mora'][i],type:'number',required:true})),...['reestructurado','refinanciado','castigado'].map(key=>({key,label:key,type:'checkbox'})),{key:'estadoCartera',label:'Estado de cartera declarado'}]},
 workflow:{title:'Aprobaciones pendientes',permission:'Workflow',columns:[]},
 rutas:{title:'Flujos de aprobación',permission:'Workflow',columns:[{key:'nombre',label:'Ruta'},{key:'prioridad',label:'Prioridad'},{key:'activa',label:'Activa'},{key:'esPredeterminada',label:'Predeterminada'}],fields:[{key:'codigo',label:'Código',required:true},{key:'nombre',label:'Nombre',required:true},{key:'prioridad',label:'Prioridad (menor primero)',type:'number',required:true},{key:'activa',label:'Ruta activa',type:'checkbox'},{key:'esPredeterminada',label:'Usar si no aplica otra ruta',type:'checkbox'}]},
 integraciones:{title:'Integraciones',permission:'Integraciones',columns:[{key:'nombre',label:'Proveedor'},{key:'tipo',label:'Servicio'},{key:'ambiente',label:'Ambiente'},{key:'estado',label:'Disponibilidad'}],fields:[{key:'ambiente',label:'Ambiente',options:['PRUEBAS','PRODUCCION'],required:true},{key:'activo',label:'Habilitado',type:'checkbox'}]}};const c=configs[this.area];this.title=c.title;this.permission=c.permission;this.columns=c.columns;this.fields=c.fields||[];this.subtitle=this.area==='auditoria'?'Actividad trazable de la empresa, sin contraseñas ni secretos.':'Información operativa y acciones de la empresa activa.';void this.load();}
 canManage(){return this.auth.can(this.permission+':Manage');}display(value:any){return value===true?'Sí':value===false?'No':value??'Sin dato';}
 endpoint(){return this.area==='rutas'?'/workflow/rutas':this.area==='desempeno'?'/prestamos/'+this.loanId+'/desempeno':'/'+this.area;}
 async load(){this.loading.set(true);this.error.set('');this.loadingOverlay.show('Cargando…');try{const query=new URLSearchParams({page:String(this.page()),size:String(this.size()),...Object.fromEntries(Object.entries(this.filters).filter(([,v])=>v))});if(this.filters['hasta'])query.set('hasta',this.filters['hasta']+'T23:59:59.999Z');const response=await firstValueFrom(this.api.get<any>(this.endpoint()+'?'+query));this.data.set(Array.isArray(response)?{}:response);this.items.set(Array.isArray(response)?response:response.items||response.rutas||response.configuraciones||[]);}catch(e){this.error.set(errorMessage(e));}finally{this.loading.set(false);this.loadingOverlay.hide();}}
 async create(){this.editingId=null;this.form.set({estado:'VIGENTE',ambiente:'PRUEBAS',activo:true,activa:true,prioridad:100,esPredeterminada:false,prestamoId:this.loanId});this.routeSteps=[{cantidadAprobacionesRequeridas:1}];await this.loadRequests();}
 async loadRequests(){if(this.area==='prestamos'&&this.auth.can('Solicitudes:Read')){try{this.requests.set((await firstValueFrom(this.api.get<{items:Row[]}>('/solicitudes?size=100'))).items);}catch(e){this.error.set(errorMessage(e));}}}
 edit(row:Row){const ids:Record<string,string>={prestamos:'prestamoId',desempeno:'desempenoCreditoId',integraciones:'empresaProveedorId'};this.editingId=row[ids[this.area]];this.form.set({...row,confirmacionHumana:false});void this.loadRequests();}
 async save(){if(this.busy())return;this.busy.set(true);this.error.set('');try{const body={...this.form()};let url=this.area==='rutas'?'/workflow/rutas':'/'+this.area;if(this.area==='rutas'){body['pasos']=this.routeSteps;body['condicionJson']=JSON.stringify(this.condition);}await firstValueFrom(this.editingId?this.api.put(url+'/'+this.editingId,body):this.api.post(url,body));this.form.set(null);this.success.set('Registro guardado.');await this.load();}catch(e){this.error.set(errorMessage(e));}finally{this.busy.set(false);}}
 async decide(row:Row,decision:string){const comment=await this.dialog.prompt('Comentario para '+decision.toLowerCase()+' el paso '+row['nombrePaso']+'. Cancelar no registra la decisión.',{title:'Registrar decisión',placeholder:'Comentario (opcional)',confirmLabel:'Registrar decisión'});if(comment===null)return;this.busy.set(true);this.success.set('');this.loadingOverlay.show('Registrando decisión…');try{await firstValueFrom(this.api.post('/workflow/pasos/'+row['aprobacionPasoId']+'/decisiones',{decision,comentario:comment}));const mensajes:Record<string,string>={APROBAR:'Paso aprobado con éxito para '+row['solicitud']+'.',DEVOLVER:'Paso devuelto — '+row['solicitud']+' vuelve a la etapa anterior para corrección.',RECHAZAR:'Solicitud '+row['solicitud']+' rechazada.'};this.success.set(mensajes[decision]??'Decisión registrada.');await this.load();}catch(e){this.error.set(errorMessage(e));}finally{this.busy.set(false);this.loadingOverlay.hide();}}
 exportar(){this.busy.set(true);this.loadingOverlay.show('Generando Excel…');try{exportCsv(this.area,this.columns.map(c=>({key:c.key,label:c.label})),this.items());}finally{this.busy.set(false);this.loadingOverlay.hide();}}
}
